// <auto-generated />
namespace WebBook.net.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bookdetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bookdetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202012062255152_bookdetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
